Sprint1
ClevertecFrontendLab/sprint1-alexeyvalko pull request #1
Opened 2023-01-28 17:15 UTC by alexeyvalko

2023-01-28 17:33 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674927189/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674927189/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674927189/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674927189/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674927189/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674927189/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674927189/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674927189/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674927189/content-window.png)

2023-01-29 08:20 UTC, dariavorom requested changes

2023-01-29 08:20 UTC, dariavorom commented on src/components/product-card/card-horizontal.tsx
> +    <ProductContainer direction='row' padding='24px 24px 24px 16px' data-test-id='card'>
переход на детальную страницы книги должен быть по клику на всю карточку (сейчас по клику по названию)

2023-01-29 08:20 UTC, dariavorom commented on src/components/product-card/product-card.tsx
> +    <ProductContainer direction='column' data-test-id='card'>
то же самое: переход на детальную страницы книги должен быть по клику на всю карточку (сейчас по клику по названию

2023-01-29 09:55 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674986122/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674986122/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674986122/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674986122/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674986122/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674986122/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674986122/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674986122/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1674986122/content-window.png)

2023-01-29 09:59 UTC, dariavorom approved these changes

2023-01-29 10:06 UTC, merged